using System.Net;
using System.Net.Http.Json;
using BetaFit.Desktop.Models;
namespace BetaFit.Desktop.Services;
public sealed class BetaFitApiException : Exception { public HttpStatusCode StatusCode { get; } public IReadOnlyDictionary<string,string[]>? ValidationErrors { get; } public BetaFitApiException(string message,HttpStatusCode statusCode,IReadOnlyDictionary<string,string[]>? errors=null):base(message){StatusCode=statusCode;ValidationErrors=errors;} }
public interface IBetaFitApiService { Task<AuthResponse> LoginAsync(LoginRequest request,CancellationToken ct=default); Task<bool> IsApiOnlineAsync(CancellationToken ct=default); Task<DashboardSummaryResponse> GetDashboardSummaryAsync(CancellationToken ct=default); Task<IReadOnlyList<CategoryResponse>> GetCategoriesAsync(bool onlyActive=false,CancellationToken ct=default); Task<CategoryResponse> CreateCategoryAsync(CreateCategoryRequest request,CancellationToken ct=default); Task<CategoryResponse> UpdateCategoryAsync(Guid id,UpdateCategoryRequest request,CancellationToken ct=default); Task ActivateCategoryAsync(Guid id,CancellationToken ct=default); Task DeactivateCategoryAsync(Guid id,CancellationToken ct=default); Task DeleteCategoryAsync(Guid id,CancellationToken ct=default); Task<PagedResponse<ProductListItemResponse>> SearchProductsAsync(string? term,Guid? categoryId,int page,int pageSize,CancellationToken ct=default); Task<ProductResponse> CreateProductAsync(CreateProductRequest request,CancellationToken ct=default); Task<ProductResponse> UpdateProductAsync(Guid id,UpdateProductRequest request,CancellationToken ct=default); Task ActivateProductAsync(Guid id,CancellationToken ct=default); Task DeactivateProductAsync(Guid id,CancellationToken ct=default); Task SetFeaturedAsync(Guid id,bool value,CancellationToken ct=default); Task DeleteProductAsync(Guid id,CancellationToken ct=default); }
public sealed class BetaFitApiService:IBetaFitApiService
{
 private readonly HttpClient _http; public BetaFitApiService(HttpClient http)=>_http=http;
 public Task<AuthResponse> LoginAsync(LoginRequest request,CancellationToken ct=default)=>SendAsync<AuthResponse>(()=>_http.PostAsJsonAsync("api/v1/auth/login",request,ct),ct);
 public async Task<bool> IsApiOnlineAsync(CancellationToken ct=default){try{using var r=await _http.GetAsync("health",ct);return r.IsSuccessStatusCode;}catch{ return false;}}
 public Task<DashboardSummaryResponse> GetDashboardSummaryAsync(CancellationToken ct=default)=>GetAsync<DashboardSummaryResponse>("api/v1/dashboard/summary",ct);
 public async Task<IReadOnlyList<CategoryResponse>> GetCategoriesAsync(bool onlyActive=false,CancellationToken ct=default)=>await GetAsync<List<CategoryResponse>>($"api/v1/categories?onlyActive={onlyActive}",ct);
 public Task<CategoryResponse> CreateCategoryAsync(CreateCategoryRequest request,CancellationToken ct=default)=>SendAsync<CategoryResponse>(()=>_http.PostAsJsonAsync("api/v1/categories",request,ct),ct);
 public Task<CategoryResponse> UpdateCategoryAsync(Guid id,UpdateCategoryRequest request,CancellationToken ct=default)=>SendAsync<CategoryResponse>(()=>_http.PutAsJsonAsync($"api/v1/categories/{id}",request,ct),ct);
 public Task ActivateCategoryAsync(Guid id,CancellationToken ct=default)=>NoContentAsync($"api/v1/categories/{id}/activate",HttpMethod.Patch,ct); public Task DeactivateCategoryAsync(Guid id,CancellationToken ct=default)=>NoContentAsync($"api/v1/categories/{id}/deactivate",HttpMethod.Patch,ct); public Task DeleteCategoryAsync(Guid id,CancellationToken ct=default)=>NoContentAsync($"api/v1/categories/{id}",HttpMethod.Delete,ct);
 public Task<PagedResponse<ProductListItemResponse>> SearchProductsAsync(string? term,Guid? categoryId,int page,int pageSize,CancellationToken ct=default){var u=$"api/v1/products?page={page}&pageSize={pageSize}";if(!string.IsNullOrWhiteSpace(term))u+=$"&searchTerm={Uri.EscapeDataString(term)}";if(categoryId.HasValue)u+=$"&categoryId={categoryId}";return GetAsync<PagedResponse<ProductListItemResponse>>(u,ct);}
 public Task<ProductResponse> CreateProductAsync(CreateProductRequest request,CancellationToken ct=default)=>SendAsync<ProductResponse>(()=>_http.PostAsJsonAsync("api/v1/products",request,ct),ct); public Task<ProductResponse> UpdateProductAsync(Guid id,UpdateProductRequest request,CancellationToken ct=default)=>SendAsync<ProductResponse>(()=>_http.PutAsJsonAsync($"api/v1/products/{id}",request,ct),ct);
 public Task ActivateProductAsync(Guid id,CancellationToken ct=default)=>NoContentAsync($"api/v1/products/{id}/activate",HttpMethod.Patch,ct); public Task DeactivateProductAsync(Guid id,CancellationToken ct=default)=>NoContentAsync($"api/v1/products/{id}/deactivate",HttpMethod.Patch,ct); public Task SetFeaturedAsync(Guid id,bool value,CancellationToken ct=default)=>NoContentAsync($"api/v1/products/{id}/featured?isFeatured={value.ToString().ToLowerInvariant()}",HttpMethod.Patch,ct); public Task DeleteProductAsync(Guid id,CancellationToken ct=default)=>NoContentAsync($"api/v1/products/{id}",HttpMethod.Delete,ct);
 private Task<T> GetAsync<T>(string u,CancellationToken ct)=>SendAsync<T>(()=>_http.GetAsync(u,ct),ct);
 private async Task<T> SendAsync<T>(Func<Task<HttpResponseMessage>> action,CancellationToken ct){try{using var r=await action();await EnsureSuccessAsync(r,ct);return await r.Content.ReadFromJsonAsync<T>(cancellationToken:ct)??throw new BetaFitApiException("A API retornou uma resposta vazia.",r.StatusCode);}catch(BetaFitApiException){throw;}catch(HttpRequestException){throw new BetaFitApiException("Não foi possível conectar à API BetaFit.",HttpStatusCode.ServiceUnavailable);}catch(TaskCanceledException){throw new BetaFitApiException("A API demorou demais para responder.",HttpStatusCode.RequestTimeout);}}
 private async Task NoContentAsync(string u,HttpMethod method,CancellationToken ct){try{using var r=await _http.SendAsync(new HttpRequestMessage(method,u),ct);await EnsureSuccessAsync(r,ct);}catch(BetaFitApiException){throw;}catch(HttpRequestException){throw new BetaFitApiException("Não foi possível conectar à API BetaFit.",HttpStatusCode.ServiceUnavailable);}catch(TaskCanceledException){throw new BetaFitApiException("A API demorou demais para responder.",HttpStatusCode.RequestTimeout);}}
 private static async Task EnsureSuccessAsync(HttpResponseMessage r,CancellationToken ct){if(r.IsSuccessStatusCode)return;ApiErrorResponse? e=null;try{e=await r.Content.ReadFromJsonAsync<ApiErrorResponse>(cancellationToken:ct);}catch{}var m=r.StatusCode switch{HttpStatusCode.Unauthorized=>"Sessão inválida ou credenciais sem permissão.",HttpStatusCode.Forbidden=>"Você não tem permissão para esta operação.",HttpStatusCode.NotFound=>"Registro não encontrado.",HttpStatusCode.Conflict=>"A operação entrou em conflito com o estado atual.",HttpStatusCode.UnprocessableEntity=>"Os dados enviados não puderam ser processados.",HttpStatusCode.BadRequest=>e?.Title??"Os dados enviados são inválidos.",_=>e?.Title??"Ocorreu um erro inesperado na API."};throw new BetaFitApiException(m,r.StatusCode,e?.Errors);}
}