namespace BetaFit.Desktop.Models;
public sealed class LoginRequest { public string Email { get; set; } = ""; public string Password { get; set; } = ""; }
public sealed class AuthResponse { public string Token { get; set; } = ""; public string Name { get; set; } = ""; public string Email { get; set; } = ""; public string Role { get; set; } = ""; }
public sealed class DashboardSummaryResponse { public int TotalProducts { get; set; } public int ActiveProducts { get; set; } public int FeaturedProducts { get; set; } public int TotalCategories { get; set; } public int ActiveCategories { get; set; } }
public sealed class CategoryResponse { public Guid Id { get; set; } public string Name { get; set; } = ""; public string Description { get; set; } = ""; public string? ImageUrl { get; set; } public bool IsActive { get; set; } public int ProductCount { get; set; } }
public sealed class CreateCategoryRequest { public string Name { get; set; } = ""; public string Description { get; set; } = ""; public string? ImageUrl { get; set; } }
public sealed class UpdateCategoryRequest { public string Name { get; set; } = ""; public string Description { get; set; } = ""; public string? ImageUrl { get; set; } }
public class ProductListItemResponse { public Guid Id { get; set; } public string Name { get; set; } = ""; public decimal Price { get; set; } public string? ImageUrl { get; set; } public string CategoryName { get; set; } = ""; public int Gender { get; set; } public bool IsFeatured { get; set; } public bool IsActive { get; set; } }
public sealed class ProductResponse : ProductListItemResponse { public string Description { get; set; } = ""; public Guid CategoryId { get; set; } }
public sealed class PagedResponse<T> { public IReadOnlyList<T> Items { get; set; } = Array.Empty<T>(); public int TotalCount { get; set; } public int Page { get; set; } public int PageSize { get; set; } public int TotalPages { get; set; } }
public sealed class CreateProductRequest { public string Name { get; set; } = ""; public string Description { get; set; } = ""; public decimal Price { get; set; } public string? ImageUrl { get; set; } public Guid CategoryId { get; set; } public int Gender { get; set; } public bool IsFeatured { get; set; } }
public sealed class UpdateProductRequest { public string Name { get; set; } = ""; public string Description { get; set; } = ""; public decimal Price { get; set; } public string? ImageUrl { get; set; } public Guid CategoryId { get; set; } public int Gender { get; set; } }
public sealed class ApiErrorResponse { public int Status { get; set; } public string? Title { get; set; } public Dictionary<string,string[]>? Errors { get; set; } }